// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSwgUUDDA58CDhzGShxJNZis5QTUaOJF0',
    appId: '1:981482182800:web:5f2503ea60707a5ca06015',
    messagingSenderId: '981482182800',
    projectId: 'test-project-d6b10',
    authDomain: 'test-project-d6b10.firebaseapp.com',
    storageBucket: 'test-project-d6b10.appspot.com',
    measurementId: 'G-FW7VRFFX4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjLD-lrjgMD-ZuHHZ7VNwPlcJ4jz02Q3w',
    appId: '1:981482182800:android:e70723b441949eb8a06015',
    messagingSenderId: '981482182800',
    projectId: 'test-project-d6b10',
    storageBucket: 'test-project-d6b10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBprgNKxj_BvEH-44i_jcHVbK4QTq0SZPQ',
    appId: '1:981482182800:ios:63e538f7463be3c5a06015',
    messagingSenderId: '981482182800',
    projectId: 'test-project-d6b10',
    storageBucket: 'test-project-d6b10.appspot.com',
    iosClientId: '981482182800-t23tmr2m9btmn937eecah4r6hevg3asf.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBprgNKxj_BvEH-44i_jcHVbK4QTq0SZPQ',
    appId: '1:981482182800:ios:63e538f7463be3c5a06015',
    messagingSenderId: '981482182800',
    projectId: 'test-project-d6b10',
    storageBucket: 'test-project-d6b10.appspot.com',
    iosClientId: '981482182800-t23tmr2m9btmn937eecah4r6hevg3asf.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );
}
