# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
  #    - uses: subosito/flutter-action@v2
   #     with:
    #      flutter-version: '3.7.7'
      - name: get today date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
     
  #    - run: flutter pub get
   #   - run: flutter test
   #   - run: flutter build apk
        #      - run: flutter build appbundle


      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        id: upload
        with:
          credentials: ${{ secrets.credentials }}
          filename: "test.txt"
          folderId: ${{ secrets.folderId }}
          overwrite: "true" # optional boolean
          mimeType: "application/vnd.android.package-archive"
      - name: Get file URL
        run: |
          echo "File URL: https://drive.google.com/uc?id=$(cat ${{ steps.upload.outputs.fileId }})"
          echo "File URL: ${{ steps.upload.outputs.fileId }}"
          echo "File URL: ${{ steps.upload.outputs }}"
          echo "File URL: ${{ steps.upload }}"
      
      - name: Send email with attachment
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          from: ${{ secrets.MY_GMAIL_USERNAME }}
          username: ${{ secrets.MY_GMAIL_USERNAME }}
          password: ${{ secrets.MY_GMAIL_PASSWORD }}
          subject: Test email with attachment
          body: Here's the file you requested.
          to: mohamed.moataz194@gmail.com
          attachments: |
            test.txt
