# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
  #    - uses: subosito/flutter-action@v2
   #     with:
    #      flutter-version: '3.7.7'
      - name: get today date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
     
  #    - run: flutter pub get
   #   - run: flutter test
   #   - run: flutter build apk
        #      - run: flutter build appbundle


      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        id: upload
        with:
          credentials: ${{ secrets.credentials }}
          filename: "test.txt"
          folderId: ${{ secrets.folderId }}
          overwrite: "true" # optional boolean
          mimeType: "application/vnd.android.package-archive"
            
      
      - name: Check if upload was successful
        run: |
          if [ -z "${{ steps.upload.outputs.url }}" ]; then
            echo "Upload failed, see logs for details."
          else
            echo "Upload succeeded: ${{ steps.upload.outputs.url }}"
          fi
          
      - name: Get file URL
        run: |
          echo "File URL: ${{ steps.upload.outputs.url }}"
   #   - uses: cinotify/github-action@main
    #    with:
     #     to: 'mohamed.moataz194@gmail.com'
      #    subject: 'test app ${{steps.date.outputs.date}}'
       #   body: 'Apk ${{ steps.upload.outputs.url }} '
