# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
  #    - uses: subosito/flutter-action@v2
   #     with:
    #      flutter-version: '3.7.7'
      - name: get today date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
     
  #    - run: flutter pub get
   #   - run: flutter test
   #   - run: flutter build apk
        #      - run: flutter build appbundle


      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        id: upload
        with:
          credentials: ${{ secrets.credentials }}
          filename: "test.txt"
          folderId: ${{ secrets.folderId }}
          overwrite: "true" # optional boolean
          mimeType: "application/vnd.android.package-archive"
      - name: Get file URL
        run: |
          echo "File URL: https://drive.google.com/uc?id=$(cat ${{ steps.upload.outputs.fileId }})"
          echo "File URL: ${{ steps.upload.outputs.fileId }}"
          echo "File URL: ${{ steps.upload.outputs }}"
          echo "File URL: ${{ steps.upload }}"
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          username: ${{secrets.MY_GMAIL_USERNAME}}
          password: ${{secrets.MY_GMAIL_PASSWORD}}
          subject: Opportunity for you
          to: mohamed.moataz194@gmail.com
          cc: mohamed.moataz194@gmail.com
          from: GitHub Campus Expert
          html_body: file://temp.html
          secure: true
          ignore_cert: true
          convert_markdown: true
          priority: low
          

      
